### ISSUE TITLE
Configure RN project to use SVGs

### ISSUE THREAD

**Issue by joebochill** [pxblue/pxblue-cli#47]
#### Describe the desired behavior
When starting a new react native project using the RNC CLI, the project should be ready to go with SVG icons out of the box.

#### Describe the current behavior
Currently, the default project is not configured to allow the use of SVG icons, so copying and pasting code snippets that includes icons will give you the red screen of death.

#### Is this request related to a current issue?
Discovered when testing the new version of the RN component library.

#### Additional Context
We need to include packages for:
- react-native-svg
- react-native-svg-transformer
- @types/react-native-vector-icons (dev dependency for typescript projects)

Then we need to follow the steps for configuring react-native-svg-transformer (https://github.com/kristerkari/react-native-svg-transformer#step-3-configure-the-react-native-packager)

**Comment by huayunh** [comment]
Maybe also add in `react-native-safe-area-context` while working on this issue...

**Comment by joebochill** [comment]
> Maybe also add in `react-native-safe-area-context` while working on this issue...

Let's add _any_ peer dependencies that are required by any of the packages we install by default.

**Comment by joebochill** [comment]
When doing the SVG setup, also remember to update the android gradle file to properly link the icons (this is why sometimes the icons don't load on android).

**Comment by joebochill** [comment]
If this is quick, we might be able to lump this in with the work we're doing to connect up the new react templates. Otherwise, we can definitely get it working when we do the RN templates.
