### ISSUE TITLE
Troubles when yarn start a ts react project

### ISSUE THREAD

**Issue by huayunh** [pxblue/pxblue-cli#48]
#### Describe the bug

It worked before but today when I was trying to use the cli for a ts project, it gives me the following message on `yarn start`:

```
Welcome.

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
USMOOWWM543G8WN:cli-test-ts c3050144$ yarn start
yarn run v1.17.3
$ react-scripts start
/Users/c3050144/Documents/pxblue/cli-test-ts/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/Users/c3050144/Documents/pxblue/cli-test-ts/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/Users/c3050144/Documents/pxblue/cli-test-ts/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But the same steps with a js flag does not induce any error and works like normal.

#### What is the expected behavior?

No error.

#### What are the steps to reproduce?
1. `npx -p @pxblue/cli@beta pxb new react --name cli-test-ts --lint --prettier --language ts --template blank`
2. `yarn start`
3. (Error message as listed above)

#### Screenshots or links to minimum reproduction example

N/A

#### Environment
MacOS, node v12.13.0

**Comment by joebochill** [comment]
Refer to https://github.com/facebook/create-react-app/issues/10117

This is an issue with CRA, not our CLI. Note that a default TS app from `npx create-react-app myapp --template=typescript` gives the same error.

Hopefully it will sort itself out if we just wait a little while.

**Comment by joebochill** [comment]
This is fixed when I tested it today
