### ISSUE TITLE
Add --alpha or --beta flag to allow easier testing of new template packages

### ISSUE THREAD

**Issue by emclaug2** [pxblue/pxblue-cli#56]
#### Describe the desired behavior
I want new flags added so I can easily test beta or alpha template packages.

#### Describe the current behavior
When selecting a template, only the latest version is pulled down. 

#### Is this request related to a current issue?
No

**Comment by jeffvg** [comment]
Look in to using --version, --beta and --alpha for this or using the '@' after the template name

**Comment by jeffvg** [comment]
moved to PXBLUE-1920
